.dashVtk_js_metadata <- function() {
deps_metadata <- list(`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vtk.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_vtk.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Algorithm.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Calculator.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-CellData.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DataArray.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-FieldData.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GeometryRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GlyphRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-ImageData.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Mesh.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PointCloudRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PointData.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PolyData.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Reader.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-ShareDataSet.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-SliceRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-View.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Volume.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeController.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeDataRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeRepresentation.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Algorithm.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Calculator.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-CellData.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DataArray.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-FieldData.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GeometryRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GlyphRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-ImageData.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Mesh.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PointCloudRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PointData.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-PolyData.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Reader.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-ShareDataSet.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-SliceRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-View.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-Volume.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeController.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeDataRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_vtk` = structure(list(name = "dash_vtk",
version = "0.0.7", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-VolumeRepresentation.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashVtk",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
